/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author turupawn
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pb_vida1 = new javax.swing.JProgressBar();
        pb_vida2 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        lbl_gameover = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PieceValkiriabltG.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PieceKnightbltG.png"))); // NOI18N

        pb_vida1.setValue(100);

        pb_vida2.setValue(100);

        jButton1.setText("Atacar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_gameover.setText("Juego en curso");

        jButton3.setText("Curarse");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Super ataque");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(90, 90, 90)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(175, 175, 175)
                        .addComponent(lbl_gameover))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(113, 113, 113)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(lbl_gameover))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        double random = Math.random()*15;
        int nueva_vida = pb_vida2.getValue()-(int)random;
        pb_vida2.setValue(nueva_vida);
        if(nueva_vida<=0)
        {
            lbl_gameover.setText("Ha ganado la valkiria");
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                
                if(ataque_random<40)
                {
                    System.out.println("Ataque normal");
                    double random = Math.random()*15;
                    int nueva_vida = pb_vida1.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<80)
                {
                    System.out.println("Curarse");
                    double random = Math.random()*15;
                    int nueva_vida = pb_vida2.getValue()+(int)random;
                    pb_vida2.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<90)
                {
                    System.out.println("Super ataque");
                    pb_vida1.setValue(1);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else
                {
                    System.out.println("Super curarse");
                    pb_vida2.setValue(100);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        double random = Math.random()*15;
        int nueva_vida = pb_vida1.getValue()+(int)random;
        pb_vida1.setValue(nueva_vida);
        if(nueva_vida<=0)
        {
            lbl_gameover.setText("Ha ganado la valkiria");
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                
                if(ataque_random<40)
                {
                    System.out.println("Ataque normal");
                    double random = Math.random()*15;
                    int nueva_vida = pb_vida1.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<80)
                {
                    System.out.println("Curarse");
                    double random = Math.random()*15;
                    int nueva_vida = pb_vida2.getValue()+(int)random;
                    pb_vida2.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<90)
                {
                    System.out.println("Super ataque");
                    pb_vida1.setValue(1);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else
                {
                    System.out.println("Super curarse");
                    pb_vida2.setValue(100);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        if(jButton4.isEnabled())
        {
            jButton4.setEnabled(false);
            int nueva_vida = pb_vida2.getValue()/2;
            pb_vida2.setValue(nueva_vida);
            if(nueva_vida<=0)
            {
                lbl_gameover.setText("Ha ganado la valkiria");
            }

            Timer timer = new Timer(1000, new AbstractAction(){
                @Override
                public void actionPerformed(ActionEvent ae){
                double ataque_random = Math.random()*100;
                
                if(ataque_random<40)
                {
                    System.out.println("Ataque normal");
                    double random = Math.random()*15;
                    int nueva_vida = pb_vida1.getValue()-(int)random;
                    pb_vida1.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<80)
                {
                    System.out.println("Curarse");
                    double random = Math.random()*15;
                    int nueva_vida = pb_vida2.getValue()+(int)random;
                    pb_vida2.setValue(nueva_vida);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else if(ataque_random<90)
                {
                    System.out.println("Super ataque");
                    pb_vida1.setValue(1);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }else
                {
                    System.out.println("Super curarse");
                    pb_vida2.setValue(100);
                    if(nueva_vida<=0)
                    {
                        lbl_gameover.setText("Ha ganado el caballero");
                    }
                }
                }
            });
            timer.setRepeats(false);
            timer.start();
        }
    }//GEN-LAST:event_jButton4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbl_gameover;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    // End of variables declaration//GEN-END:variables
}
